// officespace-frontend/src/app/shared/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss',
})
export class NavbarComponent {
  constructor(public auth: AuthService, private router: Router) {}

  logout(): void {
    this.auth.logout().subscribe({ error: () => this.auth.clearSession() });
    this.router.navigate(['/login']);
  }
}

<nav class="navbar" *ngIf="auth.isAuthenticated()">
  <div class="navbar-brand">
    <a routerLink="/search">OfficeSpace</a>
  </div>
  <ul class="navbar-links">
    <li><a routerLink="/search" routerLinkActive="active">Buscar espacios</a></li>
    <li><a routerLink="/booking/my-bookings" routerLinkActive="active">Mis reservas</a></li>
    <li *ngIf="auth.isAdmin()">
      <a routerLink="/admin" routerLinkActive="active">Administración</a>
    </li>
  </ul>
  <div class="navbar-user">
    <span>{{ (auth.currentUser$ | async)?.name }}</span>
    <button (click)="logout()" class="btn-logout">Cerrar sesión</button>
  </div>
</nav>

// frontend/src/components/Navbar.jsx
import { NavLink, useNavigate } from "react-router-dom";
import { clearSession, getUser } from "../utils/authStorage";

export default function Navbar() {
  const navigate = useNavigate();
  const user = getUser();

  function handleLogout() {
    clearSession();
    navigate("/login");
  }

  return (
    <nav className="navbar">
      <div className="navbar-brand">OfficeSpace</div>

      <div className="nav-links">
        <NavLink
          to="/spaces"
          className={({ isActive }) => (isActive ? "active-link" : "")}
        >
          Buscar espacios
        </NavLink>

        <NavLink
          to="/bookings/my"
          className={({ isActive }) => (isActive ? "active-link" : "")}
        >
          {user?.role === "ADMINISTRADOR" ? "Todas las reservas" : "Mis reservas"}
        </NavLink>

        {user?.role === "ADMINISTRADOR" && (
          <NavLink
            to="/admin"
            className={({ isActive }) => (isActive ? "active-link" : "")}
          >
            Administración
          </NavLink>
        )}

        <span className="nav-user">{user?.email}</span>

        <button className="logout-button" onClick={handleLogout}>
          Cerrar sesión
        </button>
      </div>
    </nav>
  );
}
